version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupword
    - errcheck
    - errorlint
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nolintlint
    - prealloc
    - revive
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: kebab
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G117
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
